type Props = {
  qrSvg: string
}

export function QRDisplay({ qrSvg }: Props) {
  return (
    <div
      className="rounded-2xl p-6"
      style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
    >
      <p className="text-sm font-medium mb-4 text-center">Tu código personal</p>
      {/* SVG is machine-generated by the qrcode library from a UUID — no user-controlled HTML */}
      <div
        className="mx-auto rounded-xl overflow-hidden"
        style={{ width: 200, height: 200 }}
        dangerouslySetInnerHTML={{ __html: qrSvg }}
      />
      <p className="text-xs text-center mt-4" style={{ color: 'var(--text-muted)' }}>
        Mostrá este código al cajero para acumular o canjear puntos
      </p>
    </div>
  )
}
