type Props = {
  qrSvg: string | null
}

export function QRDisplay({ qrSvg }: Props) {
  return (
    <div
      className="rounded-2xl p-6"
      style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
    >
      <p className="text-sm font-medium mb-4 text-center">Tu código personal</p>
      {qrSvg ? (
        /* SVG is machine-generated by the qrcode library from a UUID — no user-controlled HTML */
        <div
          className="mx-auto rounded-xl overflow-hidden"
          style={{ width: 200, height: 200 }}
          dangerouslySetInnerHTML={{ __html: qrSvg }}
        />
      ) : (
        <div
          className="mx-auto rounded-xl flex items-center justify-center text-xs text-center"
          style={{ width: 200, height: 200, background: 'var(--border)', color: 'var(--text-muted)' }}
        >
          QR no disponible
        </div>
      )}
      <p className="text-xs text-center mt-4" style={{ color: 'var(--text-muted)' }}>
        Mostrá este código al cajero para acumular o canjear puntos
      </p>
    </div>
  )
}
